# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|

  config.vm.define :docker1 do |docker1|
    docker1.vm.box = "docker-7.4"
    docker1.vm.hostname = "docker1"
    docker1.vm.network "private_network", ip: "192.168.10.10"
    #docker1.vm.synced_folder "d:/data/vagrant/docker", "/docker"
    docker1.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = "1024"
      vb.cpus = 1
    end
    #docker1.vm.provision "shell", run: "always", inline: <<-SHELL
    #  systemctl restart network
    #SHELL
    docker1.vm.provision "shell" do |s|
      s.path = "script.sh"
      #s.args = ["docker1", "--bip=10.1.10.1/24"]
      s.args = ["docker1"]
    end
    #docker1.vm.provision "shell", path: "script.sh"
  end


  config.vm.define :docker2 do |docker2|
    docker2.vm.box = "docker-7.4"
    docker2.vm.hostname = "docker2"
    docker2.vm.network "private_network", ip: "192.168.10.11"
    #docker2.vm.synced_folder "d:/data/vagrant/docker", "/docker"
    docker2.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = "1024"
      vb.cpus = 1
    end
    #docker2.vm.provision "shell", run: "always", inline: <<-SHELL
    #  systemctl restart network
    #SHELL
    docker2.vm.provision "shell" do |s|
      s.path = "script.sh"
      #s.args = ["docker2", "--bip=10.1.20.1/24"]
      s.args = ["docker2"]
    end
  end
    
end
