apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 192.168.10.6
networking:
#  dnsDomain: myk8s.com
  podSubnet: 10.244.0.0/16
etcd:
  endpoints:
  - http://192.168.10.6:2379
  - http://192.168.10.7:2379
  - http://192.168.10.8:2379
kubernetesVersion: v1.6.2
