# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

k8s_master_ip = "192.168.11.6"
k8s_node1_ip = "192.168.11.7"
k8s_node2_ip = "192.168.11.8"
host_ip = "192.168.11.1"
username = "dave.zhao"
password = ""

Vagrant.configure("2") do |config|

  config.vm.define :k8s_master do |k8s_master|
    k8s_master.vm.box = "hyperv-7.3"
    #k8s_master.vm.hostname = "k8s-master"
    #k8s_master.vm.network "private_network", ip: "192.168.10.6"
    k8s_master.vm.network "private_network", ip: k8s_master_ip, auto_config: false
    #k8s_master.vm.synced_folder "d:/data/vagrant/docker", "/docker", type: "smb", mount_options: ["username=dave.zhao","password="]

    k8s_master.vm.provider "hyperv" do |vb|
      #vb.gui = true
      vb.ip_address_timeout = 480
      vb.memory = "2048"
      vb.cpus = 2
    end

    # k8s_master.vm.provision "shell", run: "always", inline: <<-SHELL
    # mkdir -p /docker > /dev/null 2>&1
    # sudo mount -t cifs -o username=#{username},password=#{password} //#{host_ip}/d/data/vagrant/docker /docker
    # SHELL

    k8s_master.vm.provision "shell" do |s|
      s.path = "script.sh"
      #s.args = ["k8s-master", "--bip=10.1.10.1/24"]
      s.args = ["k8s-master", "#{k8s_master_ip}"]
    end
    #k8s_master.vm.provision "shell", path: "script.sh"
  end

  # config.vm.define :k8s_node1 do |k8s_node1|
  #   k8s_node1.vm.box = "hyperv-7.3"
  #   #k8s_node1.vm.hostname = "k8s-node1"
  #   #k8s_node1.vm.network "private_network", ip: "192.168.10.6"
  #   k8s_node1.vm.network "private_network", ip: k8s_node1_ip, auto_config: false

  #   k8s_node1.vm.provider "hyperv" do |vb|
  #     #vb.gui = true
  #     #vb.vswitch = "NATSwitch"
  #     vb.ip_address_timeout = 480
  #     vb.memory = "1024"
  #     vb.cpus = 1
  #   end

  #   k8s_node1.vm.provision "shell", run: "always", inline: <<-SHELL
  #   mkdir -p /docker > /dev/null 2>&1
  #   sudo mount -t cifs -o username=#{username},password=#{password} //#{host_ip}/d/data/vagrant/docker /docker
  #   SHELL

  #   k8s_node1.vm.provision "shell" do |s|
  #     s.path = "script.sh"
  #     #s.args = ["k8s-node1", "--bip=10.1.10.1/24"]
  #     s.args = ["k8s-node1", "#{k8s_node1_ip}"]
  #   end
  #   #k8s_node1.vm.provision "shell", path: "script.sh"
  # end

  # config.vm.define :k8s_node2 do |k8s_node2|
  #   k8s_node2.vm.box = "hyperv-7.3"
  #   #k8s_node2.vm.hostname = "k8s-node2"
  #   #k8s_node2.vm.network "private_network", ip: "192.168.10.6"
  #   k8s_node2.vm.network "private_network", ip: k8s_node2_ip, auto_config: false
  #   #k8s_node2.vm.synced_folder "d:/data/vagrant/docker", "/docker"

  #   k8s_node2.vm.provider "hyperv" do |vb|
  #     #vb.gui = true
  #     #vb.vswitch = "NATSwitch"
  #     vb.ip_address_timeout = 480
  #     vb.memory = "1024"
  #     vb.cpus = 1
  #   end

  #   k8s_node2.vm.provision "shell", run: "always", inline: <<-SHELL
  #   mkdir -p /docker > /dev/null 2>&1
  #   sudo mount -t cifs -o username=#{username},password=#{password} //#{host_ip}/d/data/vagrant/docker /docker
  #   SHELL

  #   k8s_node2.vm.provision "shell" do |s|
  #     s.path = "script.sh"
  #     #s.args = ["k8s-node2", "--bip=10.1.10.1/24"]
  #     s.args = ["k8s-node2", "#{k8s_node2_ip}"]
  #   end
  #   #k8s_node2.vm.provision "shell", path: "script.sh"
  # end
  
end
