# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
SHADOWSOCKS_IP = "192.168.102.143"

Vagrant.configure("2") do |config|

  config.vm.define :minikube do |minikube|
    minikube.vm.box = "centos-7.4"
    minikube.vm.hostname = "minikube"
    minikube.vm.network "private_network", ip: "192.168.10.6"
    #minikube.vm.synced_folder "d:/data/vagrant/docker", "/docker"
    minikube.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = "1024"
      vb.cpus = 1
    end
    minikube.vm.provision "shell", run: "always", inline: <<-SHELL
      systemctl restart network
    SHELL
    minikube.vm.provision "shell" do |s|
      s.path = "script.sh"
      #s.args = ["k8s-master", "--bip=10.1.10.1/24"]
      s.args = ["k8s-master", SHADOWSOCKS_IP]
    end
    #minikube.vm.provision "shell", path: "script.sh"
  end

  
end
