# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  #config.vm.box = "ubuntu-1610"
  #config.vm.hostname = "mydocker"
  #config.vm.network "private_network", ip: "192.168.10.9"
#
  #config.vm.synced_folder "/data/docker/registry", "/docker/registry"
  #config.vm.synced_folder "/data/docker/works", "/docker/works"
#
  #config.vm.provider "virtualbox" do |vb|
  #  #vb.gui = true
  #  vb.memory = "1024"
  #end
  #
  #config.vm.provision "shell", run: "always", inline: <<-SHELL
  #  systemctl restart network
  #SHELL
  #config.vm.provision "shell", path: "script.sh"

  #config.vm.define :zhaoxy do |zhaoxy|
  #  zhaoxy.vm.box = "ubuntu-1610"
  #  zhaoxy.vm.hostname = "zhaoxy.com"
  #  zhaoxy.vm.network "private_network", ip: "192.168.10.9"
  #  #zhaoxy.vm.synced_folder "/data/docker", "/docker"
  #  #zhaoxy.vm.synced_folder "/data/docker/registry", "/docker/registry"
  #  #zhaoxy.vm.synced_folder "/data/docker/works", "/docker/works"
  #  #zhaoxy.vm.synced_folder "/data/docker/k8s", "/docker/k8s"
  #  zhaoxy.vm.provider "virtualbox" do |vb|
  #    #vb.gui = true
  #    vb.memory = "1024"
  #  end
  #  zhaoxy.vm.provision "shell", run: "always", inline: <<-SHELL
  #    systemctl restart network
  #  SHELL
  #  zhaoxy.vm.provision "shell" do |s|
  #    s.path = "script.sh"
  #    s.args = ["--bip=10.1.10.1/24", "zhaoxy.com"]
  #  end
  #  #zhaoxy.vm.provision "shell", path: "script.sh"
  #end

  config.vm.define :k8s_master do |k8s_master|
    k8s_master.vm.box = "ubuntu-1610"
    k8s_master.vm.hostname = "k8s-master"
    k8s_master.vm.network "private_network", ip: "192.168.10.6"
    k8s_master.vm.synced_folder "d:/data/vagrant/docker", "/docker"
    k8s_master.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = "2048"
      vb.cpus = 1
    end
    #k8s_master.vm.provision "shell", run: "always", inline: <<-SHELL
    #  systemctl restart network
    #SHELL
    #k8s_master.vm.provision "shell" do |s|
    #  s.path = "script.sh"
    #  #s.args = ["--bip=10.1.10.1/24"]
    #end
    k8s_master.vm.provision "shell", path: "script.sh"
  end

  config.vm.define :k8s_node1 do |k8s_node1|
    k8s_node1.vm.box = "ubuntu-1610"
    k8s_node1.vm.hostname = "k8s-node1"
    k8s_node1.vm.network "private_network", ip: "192.168.10.7"
    k8s_node1.vm.synced_folder "d:/data/vagrant/docker", "/docker"
    k8s_node1.vm.provider "virtualbox" do |vb|
      #vb.gui = true
      vb.memory = "2048"
      vb.cpus = 1
    end
    #k8s_node1.vm.provision "shell", run: "always", inline: <<-SHELL
    #  systemctl restart network
    #SHELL
    #k8s_node1.vm.provision "shell" do |s|
    #  s.path = "script.sh"
    #  #s.args = ["--bip=10.1.10.1/24"]
    #end
    k8s_node1.vm.provision "shell", path: "script.sh"
  end
  
end
